[package]
name = "you-better-work-bash"
version = "0.1.1"
authors = ["joaopsantos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.4"